name: image_picker_example
description: Demonstrates how to use the image_picker plugin.
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  img_picker_android:
    git:
     url: https://github.com/saravanakumar007/image_picker_android.git
     ref: main
  img_picker_platform_interface:
   git:
     url: https://github.com/saravanakumar007/image_picker_platform_interface.git
     ref: main
  mime: ^1.0.4
  video_player: ^2.1.4

dev_dependencies:
  build_runner: ^2.1.10
  espresso: ^0.2.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
