name: img_picker_android
description: Android implementation of the img_picker plugin.
repository: https://github.com/saravanakumar007/image_picker_android
issue_tracker: https://github.com/saravanakumar007/image_picker_android/issues

version: 1.0.1

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

flutter:
  plugin:
    implements: image_picker
    platforms:
      android:
        package: io.flutter.plugins.imagepicker
        pluginClass: ImagePickerPlugin
        dartPluginClass: ImagePickerAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  img_picker_platform_interface: ^2.9.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  pigeon: ^9.2.5

topics:
  - camera
  - image-picker
  - files
  - file-selection
